### ISSUE TITLE
TimelineJS hangs if the input date is in arabic digits

### ISSUE THREAD

**Issue by AurangZ** [NUKnightLab/TimelineJS#802] opened 2015-06-19 15:07 UTC
Thanks guys for the great work, the presentation is fantastic, and I don't see any other package that did such an amazing work. I am working on a project that needs a timeline and I found your package very appealing to the format. Once it's done, I will post the credit on the website. There is one little issue that seems to be easy to fix however. When you put the date in arabic digits, the timeline will not be generated and the console output is as follows (enabling the debug):
    `INIT 
    /libs/timeline/latest/js/timeline.js?2.24:334 VERSION 2.24
    /libs/timeline/latest/js/timeline.js?2.24:334 VMM.Timeline.TimeNav
    /libs/timeline/latest/js/timeline.js?2.24:334 SET DATE LANGUAGE
    /libs/timeline/latest/js/timeline.js?2.24:334 showMessege بارگذاری، شکیبا باشید...
    /libs/timeline/latest/js/timeline.js?2.24:334 DATA SOURCE: GOOGLE SPREADSHEET
    /libs/timeline/latest/js/timeline.js?2.24:334 showMessege Parsing Google Doc Data
    /libs/timeline/latest/js/timeline.js?2.24:334 showMessege Finished Parsing Data
    /libs/timeline/latest/js/timeline.js?2.24:334 onDataReady
    /libs/timeline/latest/js/timeline.js?2.24:334 showMessege Building Dates
    /libs/timeline/latest/js/timeline.js?2.24:334 UPDATE SIZE
    /libs/timeline/latest/js/timeline.js?2.24:334 HAS STARTPAGE
    /libs/timeline/latest/js/timeline.js?2.24:334 Invalid Date
    /libs/timeline/latest/js/timeline.js?2.24:7594 Uncaught TypeError: Cannot read property 'startdate' of     undefined`

I looked at the code and it seems like before parsing the date you can use python's unicode.translate to convert the text and numbers back to latin.

Cheers,
Aurang

**Comment by JoeGermuska** [comment] 2015-06-19 15:56
There is no python code involved in the deployed TimelineJS system. It is only used to manage the development and deployment of the website and the CDN resources.

Here is [one method for converting](http://stackoverflow.com/questions/1675786/convert-from-english-digits-to-arabic-ones-in-html-page) from digits used in written arabic (which are not what English speakers mean by [arabic numerals](https://en.wikipedia.org/wiki/Arabic_numerals)

This is effectively a duplicate of #800 and the answer given there holds. We won't be changing the version of Timeline associated with this Github repo to handle dates in any other system. We have a ticket (NUKnightLab/TimelineJS3#83) to consider trying to support other calendars. As for parsing dates written in other number systems, we have a new spreadsheet format for TimelineJS3 which should eliminate any ambiguity about dates, and which might make it possible to accept non-"arabic" numerals.

**Closed by JoeGermuska** 2015-06-19 15:56 UTC
