### ISSUE TITLE
Vertical images (jpg) are displaying horizontally

### ISSUE THREAD

**Issue by tlockett** [NUKnightLab/TimelineJS#810] opened 2015-07-22 19:08 UTC
Several of our vertical images are displaying horizontally. Does anyone know why this is and how we can correct it?

**Comment by JoeGermuska** [comment] 2015-07-22 19:24
duplicate of #809. Please use http://knightlab.zendesk.com and provide more details.

**Closed by JoeGermuska** 2015-07-22 19:24 UTC
